owner: BitDEVil2K16-Club # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: BitDEVil2K16 Club
    url: https://bitdevil2k16.club
    icon: https://bitdevil2k16.club/favicon.ico
  - name: RageServer-V (GTA-V)
    url: $SECURE
    icon: https://bitdevil2k16.club/favicon.ico
  - name: Liberty GameServer
    url: $LIBERTY
    icon: https://bitdevil2k16.club/favicon.ico
  - name: WIKI (RSV)
    url: https://wiki.bitdevil2k16.club
    icon: https://wiki.bitdevil2k16.club/favicon.ico
  - name: Datacenter (IFPS)
    url: https://datacenter.bitdevil2k16.club
    icon: https://datacenter.bitdevil2k16.club/favicon.ico

status-website:
  theme: night
  cname: stats.bitdevil2k16.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status - BitDEVil2K16
  introTitle: "Service Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: BitDEVil2K16 Club
      href: https://BitDEVil2K16.club
      
 i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme sind betriebsbereit
  incidentReport: "Vorfall #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Vorfall $NUMBER Details
  incidentDetails: Vorfall Details
  incidentFixed: Behoben
  incidentOngoing: Laufend
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentSubscribe: Abbonieren für Updates
  incidentViewOnGitHub: Auf GitHub anschauen
  incidentCommentSummary: Gepostet am $DATE von $AUTHOR
  incidentBack: ← zurück
  pastIncidents: Letzte Vorfälle
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Durchschnitliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-tage antwortzeit
  responseTimeMs: Antwortzeit (ms)
  up: Up
  down: Down
  degraded: Verschlechtert
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Die Seite ist [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  errorText: Versuche es in wenigen minuten erneut.
  errorHome: Zur Startseite
  pastScheduledMaintenance: Vergangene geplante Wartungen
  scheduledMaintenance: Geplante Wartung
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION minuten
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Gestartet am
  startsAt: Starten am
  duration: Duration
  durationMin: $DURATION minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplante
