owner: BitDEVil2K16-Club # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: BitDEVil2K16 Club
    url: https://bitdevil2k16.club
  - name: RageServer-V (GTA-V)
    url: $SECURE
  - name: Liberty GameServer
    url: $LIBERTY
  - name: WIKI (RSV)
    url: https://wiki.bitdevil2k16.club
  - name: Datacenter (IFPS)
    url: https://datacenter.bitdevil2k16.club

status-website:
  theme: night
  cname: stats.bitdevil2k16.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status - BitDEVil2K16
  introTitle: "Service Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: BitDEVil2K16 Club
      href: https://BitDEVil2K16.club
