owner: BitDEVil2K16-Club # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: BitDEVil2K16 Club
    url: https://bitdevil2k16.club
    icon: https://bitdevil2k16.club/favicon.ico
  - name: RageServer-V (GTA-V)
    url: $SECURE
    icon: https://bitdevil2k16.club/favicon.ico
  - name: Liberty GameServer
    url: $LIBERTY
    icon: https://bitdevil2k16.club/favicon.ico
  - name: WIKI (RSV)
    url: https://wiki.bitdevil2k16.club
    icon: https://wiki.bitdevil2k16.club/favicon.ico
  - name: Datacenter (IFPS)
    url: https://datacenter.bitdevil2k16.club
    icon: https://datacenter.bitdevil2k16.club/favicon.ico

status-website:
  theme: night
  cname: stats.bitdevil2k16.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status - BitDEVil2K16
  introTitle: "Service Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: BitDEVil2K16 Club
      href: https://BitDEVil2K16.club

i18n:
  url: "URL"
  status: "Status"
  history: "History"
  up: "🟩 Verfügbar"
  degraded: "🟨 Beeinträchtigt"
  down: "🟥 Nicht Verfügbar"
  responseTimeGraphAlt: "Antwortzeit graph"
  ms: "ms"
  responseTime: "Antwortzeit"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  uptime: "Allzeitverfügbarkeit"
  uptimeDay: "24-Stunden verfügbarkeit"
  uptimeWeek: "7-Tage verfügbarkeit"
  uptimeMonth: "30-Tage verfügbarkeit"
  uptimeYear: "1-Jahr verfügbarkeit"
  liveStatus: "Live Status"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "Alle Systeme sind betriebsbereit"
  degradedPerformance: "Beeinträchtigte Leistung"
  completeOutage: "Kompletter Ausfall"
  partialOutage: "Teilausfall"
  activeIncidents: "Aktive Vorfälle"
  incidentReport: "Vorfall #$NUMBER report →"
  incidentTitle: "Vorfall $NUMBER Details"
  incidentDetails: "Vorfall Details"
  incidentFixed: "Behoben"
  incidentOngoing: "Laufend"
  incidentOpenedAt: "Geöffnet am"
  incidentClosedAt: "Geschlossen am"
  incidentSubscribe: "Abbonieren für Updates"
  incidentViewOnGitHub: "Auf GitHub anschauen"
  incidentCommentSummary: "Gepostet am $DATE von $AUTHOR"
  incidentBack: "← zurück"
  pastIncidents: "Letzte Vorfälle"
  pastIncidentsResolved: "Resolved in $MINUTES minutes with $POSTS posts"
  overallUptime: "Gesamtverfügbarkeit: $UPTIME"
  overallUptimeTitle: "Gesamtverfügbarkeit"
  averageResponseTime: "Durchschnitliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: "Durchschnittliche Antwort"
  sevelDayResponseTime: "7-tage antwortzeit"
  responseTimeMs: "Antwortzeit (ms)"
  footer: "Die Seite ist [open source]($REPO), powered by [Upptime](https://upptime.js.org)"
  pastScheduledMaintenance: "Vergangene geplante Wartungen"
  scheduledMaintenance: "Geplante Wartung"
  scheduledMaintenanceSummaryStarted: "Gestartet am $DATE für $DURATION minuten"
  scheduledMaintenanceSummaryStarts: "Starts at $DATE for $DURATION minutes"
  startedAt: "Gestartet am"
  startsAt: "Starten am"
  duration: "Dauer"
  durationMin: "$DURATION minuten"
  incidentCompleted: "Vorfall Abgeschlossen"
  incidentScheduled: "Vorfall Geplant"
